name: ders_programi_app
description: "Universite ders programı ve ajanda uygulaması."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  shared_preferences: ^2.2.0

  # Arayuz ve Fontlar
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^22.3.1
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true